context:
  version: "0.1.0"

package:
  name: shell
  version: ${{ version }}

source:
  url: https://github.com/prefix-dev/shell/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0eb58c974361144279e966b072bc69ab0b885090ca63a60bccab11c29ac44ba9

build:
  number: 0
  script: |
    set -ex
    cd crates/shell
    cargo install --no-track --locked --bins --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}

tests:
  - script:
    - shell --help

about:
  homepage: https://github.com/prefix-dev/shell
  license: MIT
  license_file: LICENSE.txt
  summary: The ultimate cross-platform, bash-like shell

extra:
  recipe-maintainers:
    - prsabahrami
    - wolfv
